apiVersion: apps/v1
kind: Deployment
metadata:
  name: compiler-deployment
  labels:
    app: compiler-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compiler-deployment
  template:
    metadata:
      labels:
        app: compiler-deployment
    spec:
      containers:
      - name: compiler-deployment
        image: asia.gcr.io/peerprep-3219/peerprep_backend_compiler:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP