apiVersion: v1
kind: Service
metadata:
  name: compiler-service
spec:
  selector:
    app: compiler-deployment
  type: ClusterIP
  ports:
   -  protocol: TCP
      # Listens on port 5000, forwards request to compiler deployment's port 3000
      port: 5000
      targetPort: 5000