version: "3"

services:
  user-management-redis:
    container_name: user-management-redis
    image: "redis:latest"
    expose:
      - 6379
    networks:
      - user-management-network
  user-management:
    container_name: user-management
    restart: unless-stopped
    build: ./user-management
    ports:
      - "4000:4000"
    env_file: ./user-management/.env
    networks:
      - user-management-network
    depends_on:
      - user-management-redis

networks:
  user-management-network:
