apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking-deployment
  labels:
    app: matchmaking-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matchmaking-deployment
  template:
    metadata:
      labels:
        app: matchmaking-deployment
    spec:
      containers:
      - name: matchmaking-deployment
        image: asia.gcr.io/peerprep-3219/peerprep_backend_matchmaking_service:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8099
          protocol: TCP