apiVersion: v1
kind: Service
metadata:
  name: matchmaking-service
spec:
  selector:
    app: matchmaking-deployment
  type: LoadBalancer
  ports:
   -  protocol: TCP
      # Listens on port 8099, forwards request to video deployment's port 8099
      port: 8099
      targetPort: 8099