apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: NodePort
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30000
