apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-deployment
  labels:
    app: video-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-deployment
  template:
    metadata:
      labels:
        app: video-deployment
    spec:
      containers:
      - name: video-deployment
        image: asia.gcr.io/peerprep-3219/peerprep_backend_video:1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          protocol: TCP
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: video-configure-map
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: video-configure-map